### ISSUE TITLE
Warning: app-helloworld/main.c:53:1: warning: control reaches end of non-void function [-Wreturn-type]

### ISSUE THREAD

**Issue by SikkiLadho** [unikraft/app-helloworld#8]
Main doesn't return anything and the main function is non-void. Please return 0 at the end of the function to resolve the issue. 
Warning: `app-helloworld/main.c:53:1: warning: control reaches end of non-void function [-Wreturn-type]`

**Comment by nderjung** [comment]
Closed via #9.
